name: print date job
on: 
  push: 
    branch: main

jobs: 
  date_print_ubuntu: 
    runs-on: ubuntu-latest
    steps:
    - run: date

  date_print_windows:
    runs-on: windows-latest
    steps: 
    - run: date

  date_print_depends:
    needs: [date_print_ubuntu, date_print_windows]
    runs_on: ubuntu-latest
    steps:
    - run:  date
